WITH y AS (
    SELECT ID, YEAR(DIFFERENTIATION_DATE) AS yr
    FROM ECOLI_DATA
),
max_data AS (
    SELECT YEAR(DIFFERENTIATION_DATE) AS yr, MAX(SIZE_OF_COLONY) AS max_size
    FROM ECOLI_DATA
    GROUP BY YEAR(DIFFERENTIATION_DATE)
)
SELECT DISTINCT y.yr AS YEAR, max_size - a.SIZE_OF_COLONY as YEAR_DEV, a.ID
FROM ECOLI_DATA a
JOIN y ON a.ID = y.ID
JOIN max_data m ON y.yr = m.yr
ORDER BY YEAR,YEAR_DEV