SELECT ID, FISH_NAME, LENGTH
FROM FISH_INFO i
JOIN (
  SELECT FISH_TYPE, MAX(LENGTH) AS max_len
  FROM FISH_INFO
  GROUP BY FISH_TYPE
) m
  ON i.FISH_TYPE = m.FISH_TYPE
 AND i.LENGTH   = m.max_len
JOIN FISH_NAME_INFO n
  ON i.FISH_TYPE = n.FISH_TYPE
ORDER BY ID;